{{- $container := or .Values.container .Values.pod.container -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "web-api.name" . }}
  namespace: {{ .Values.team }}
  labels:
    app: {{ template "web-api.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    environment: {{ .Values.environment }}
    version: {{ quote .Values.image.version }}
spec:
  {{- include "web-api.replicaCount" . | indent 2}}
  selector:
      matchLabels:
        app: {{ template "web-api.name" . }}
        release: {{ .Release.Name }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: {{ template "web-api.name" . }}
        release: {{ .Release.Name }}
        version: {{ quote .Values.image.version }}
      annotations:
        config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if .Values.pod.annotations}}
      {{.Values.pod.annotations | toYaml | indent 2 -}}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}/{{ default .Values.nameOverride .Values.image.name }}:{{ .Values.image.version }}
          {{- include "web-api.imagePullPolicy" . | indent 10}}
          {{- if $container.command }}
          command: {{ $container.command }}
          {{- end }}
          {{- if $container.args }}
          args: {{ $container.args }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
          {{- if .Values.service.livenessProbe }}
{{ toYaml .Values.service.livenessProbe | indent 12 }}
          {{- else }}
            httpGet:
              path: {{ .Values.service.isAlivePath }}
              port: {{ .Values.service.internalPort }}
          {{- end }}
          readinessProbe:
          {{- if .Values.service.readinessProbe }}
{{ toYaml .Values.service.readinessProbe | indent 12 }}
          {{- else }}
            httpGet:
              path: {{ .Values.service.isAlivePath }}
              port: {{ .Values.service.internalPort }}
          {{- end }}
          resources:
{{ include "web-api.resources" . | indent 8 }}
          envFrom:
           - configMapRef:
              name: {{ template "web-api.name" . }}
        {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ toYaml .Values.imagePullSecrets }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}